Release version 0.1.5
pvoborni/mrack pull request #34
Opened 2020-09-24 12:31 UTC by Tiboris

Bug fixing and testing:

    Remove false warnings produced by isort
    Add missing beaker job status
    ansible-inventory: rework generation of groups

Signed-off-by: Tibor Dudlák <tdudlak@redhat.com>

2020-09-24 12:33 UTC, netoarmando approved these changes

2020-09-24 12:37 UTC, netoarmando requested changes
With @Tiboris after quick chat we decided release can wait until we finish one more commit.

2020-09-29 12:26 UTC, Tiboris commented
I have added commits:

    Refactor providers to share same code
    Force black version to get rid of test errors

2020-09-29 12:26 UTC, netoarmando approved these changes

2020-09-29 12:28 UTC, merged